### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by ThaDeveloper**
**What in this pull request?**
Testcases for User, Business and Review classes.
### Running the tests
install flask: ```pip install flask```
Install pytest : ```pip install pytest-flask```
Then run ```pytest```

### CODE REVIEW

**Comment by victorjambo** [comment]
Looks good to me. Proceed

**Comment by daktari01** [comment]
Very nice user interface. Good conformity to Git workflow

**Comment by daktari01** [comment]
Good job on posting the reviews. However, one can still post spaces as a review. Kindly work on ensuring that only relevant text is allowed.

**Comment by victorjambo** [comment]
@daktari01 We are working fixing the bug with @ThaDeveloper. The issue will be fixed before the next sprint planning

**Comment by ThaDeveloper** [comment]
@daktari01 @victorjambo It's not a bug per se, it was purely intentional. I saw it nice to give the user an option to just give a brief review( only title) without having to go ahead and expand on the same.

**Pull request merged**
